apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-kubecost-lab
  region: us-east-1
  version: "1.29"

managedNodeGroups:
  - name: ng-general
    instanceType: t3.large
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 50
    ssh:
      allow: false
    labels:
      role: general
    tags:
      Project: eksctl-kubecost-finops